### ISSUE TITLE
Column-wise rules?

### ISSUE THREAD

**Issue by ggaemo** [WellyZhang/CoPINet#1]
In the RAVEN dataset paper, it says that row-wise rules were applied. But in the code of CoPINet, column-wise rules are also taken into consideration.

Is this for the PGM dataset? Or is the column-wise rules also applied in the RAVEN dataset?

**Comment by WellyZhang** [comment]
The network considers both column-wise and row-wise features so that it can
be applied to both RAVEN and PGM. But for RAVEN, there are row-wise rules
only.
